name: deploy1.yml
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: SetUP Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Bump Major Version
        id: bump
        run: |
          set -e 
          mvn -B -q build-helper:parse-version versions:set \
                       -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0 \
                       -DprocessAllModules -DgenerateBackupPoms=false
          
          
            VER="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"
            echo "Nova Versão: $VER"
            echo "version=$VER" >> "$GITHUB_OUTPUT"
      - name: Build Project
        run: mvn -B -DskipTests package
      - name: Copy Artefato
        run: | 
          cp target/*.jar docker/app.jar
          ls docker/
      - name: Gerar Imagem Docker
        run: |
          cd docker
          docker build . -t leogloriainfnet/cervejaria-acme-ele:${{steps.bump.outputs.version}}
      - name: Gerar TAG de LATEST
        run: |
          docker tag  leogloriainfnet/cervejaria-acme-ele:${{steps.bump.outputs.version}} leogloriainfnet/cervejaria-acme-ele:latest
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Docker push Version
        run: |
          docker push leogloriainfnet/cervejaria-acme-ele:${{steps.bump.outputs.version}}
      - name: Docker push LAtest
        run: |
          docker push leogloriainfnet/cervejaria-acme-ele:latest
      - name: Commit POM.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "githubbot ci: bump para a versao ${{steps.bump.outputs.version}}"
          file_pattern: 'pom.xml'
      - name: ADD SSH KEY
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Deploy on EC2 (run.sh)
        run: |
          set -euo pipefail

                    PORT="${{ secrets.EC2_SSH_PORT || 22 }}"
                    USER=ec2-user
                    HOST=ec2-44-245-179-63.us-west-2.compute.amazonaws.com

                    echo "Conectando no $HOST e rodando run.sh"

                    ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER@$HOST" "echo conectado; uname -a"

                    # Executa o script no remoto com a versão injetada
                    ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER@$HOST" \
                      "chmod +x /home/ec2-user/run.sh && /home/ec2-user/run.sh"