name: running_sonar.yml
on:
#  schedule:
#    - "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JAVA
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup MAVEN
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
          cache: maven
      - name: Cache Do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{runner.os}}-java21-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            m2-${{runner.os}}-java21-
            m2-${{runner.os}}
      - name: Cache Do Sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{runner.os}}-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            sonar-${{runner.os}}
      - name: Realiza Analise do Sonar
        run: |
          mvn clean verify -q -DskipTests sonar:sonar -Dsonar.projectKey=Cervejaria-ACME -Dsonar.projectName='Cervejaria ACME' -Dsonar.host.url=http://ec2-35-90-57-172.us-west-2.compute.amazonaws.com:9000 -Dsonar.token=${{secrets.SONAR_TOKEN}}
          
          
